[default]
# jwt_secret = "aaaaaaaaaaaaaaaaaazzzxxs"
# limits = {"file/avif" = "1Mib", "file/gif" = "1Mib", "file/jpg" = "1Mib", "file/jpeg" = "1Mib", "file/png" = "1Mib", "file/svg" = "1Mib", "file/webp" = "1Mib", "file/webm" = "64Mib", "file/mp4" = "64Mib", "file/mpeg4" = "64Mib", "file/mpg" = "64Mib", "file/mpeg" = "64Mib", "file/mov" = "64Mib"}
log_level = "normal"
temp_dir = "/tmp"
secret_key = "0dfae96395e2c8faeb5b81e982d75ee39e928ab39a1154e22a77d655b8711686dc91c81353ca885a08bff988"
# template_dir = "src/views"
# openssl rand -hex 44

[default.database.main_connection]
url = "postgres://postgres:postgres@postgres/somedb0001"



[debug]

[debug.databases.main_connection]
url = "postgres://postgres:postgres@postgres/somedb0001"

[release]
